version: '3'

includes:
  image:dev:
    taskfile: ./common/taskfiles/podman.tasks.yml
    vars:
      IMAGE_NAME: '{{.IMAGE_NAME | default "dev"}}'
      CONTAINERFILE: ./images/dev/Containerfile
      EXPECTED_CONFIG: ./images/dev/versions.yml
