version: "3"

includes:
  image:dev:
    taskfile: ./common/taskfiles/podman.tasks.yml
    vars:
      IMAGE_NAME: '{{.IMAGE_NAME | default "dev"}}'
      CONTAINERFILE: ./images/dev/Containerfile
      EXPECTED_CONFIG: ./images/dev/versions.yml
      # Classic token with `read:packages` scope for avoiding rate limiting on
      # GitHub Packages installations via ubi.
      PODMAN_OPTS: "--secret id=github_token,src=images/dev/resources/secrets/github_token,type=file"
