FROM ubuntu:26.04

# Replace dash with bash
RUN ln -sf /usr/bin/bash /usr/bin/sh

COPY \
  images/dev/resources/systemd-256-wsl-fix.conf \
  /etc/systemd/system/user@.service.d/99-no-delegate.conf

RUN \
  # Cache dependencies outside of the container, e.g., in
  # /var/tmp/buildah-cache-$(id -u)
  --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
  --mount=target=/var/cache/apt,type=cache,sharing=locked \
  set -xe; \
  rm -f /etc/apt/apt.conf.d/docker-clean; \
  apt-get update; \
  apt-get upgrade --yes; \
  apt-get install --yes --no-install-recommends \
    # Core system utilities
    ca-certificates \
    locales \
    lsb-release \
    sudo \
    systemd \
    tzdata \
    uidmap \
    # Development tools
    build-essential \
    clang \
    make \
    git \
    git-lfs \
    gitk \
    jq \
    python3 \
    # Networking and connectivity
    dnsutils \
    inetutils-ping \
    iproute2 \
    ssh \
    curl \
    wget \
    # Container tools
    buildah \
    catatonit \
    podman \
    # Container storage
    containers-storage \
    fuse-overlayfs \
    # Container networking
    aardvark-dns \
    iptables \
    netavark \
    nftables \
    passt \
    slirp4netns \
    # Monitoring and diagnostics
    bat \
    btop \
    duf \
    lsof \
    # Productivity and utilities
    fontconfig \
    less \
    postgresql-client \
    ripgrep \
    tmux \
    unzip \
    vim \
    zip \
    zsh \
    # Other package managers
    snapd \
    ; \
  # Install universal binary installer (ubi)
  curl --silent --location \
    https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh | \
    TAG=v0.10.0 sh; \
  locale-gen en_GB.UTF-8; \
  update-locale LANG=en_GB.UTF-8; \
  ln -sf /usr/bin/batcat /usr/bin/bat; \
  ln -sf /usr/bin/python3 /usr/bin/python;

ENV UV_TOOL_DIR=/opt/uv/tools
ENV UV_TOOL_BIN_DIR=/usr/local/bin
COPY \
  common/resources/tmp/ \
  /tmp/

RUN --mount=type=secret,id=github_token \
  export GITHUB_TOKEN=$(cat /run/secrets/github_token); \
  set -xe; \
  UBI_OPTS="--in /usr/local/bin --verbose"; \
  ubi --project astral-sh/uv --exe uv $UBI_OPTS; \
  ubi --project astral-sh/uv --exe uvx $UBI_OPTS; \
  uv tool install pre-commit; \
  uv tool install tldr; \
  uv tool install tmuxp; \
  bash /tmp/scripts/install-fonts.sh; \
  bash /tmp/scripts/install-d2.sh; \
  ubi --project moonrepo/proto $UBI_OPTS; \
  ubi --project moonrepo/moon $UBI_OPTS; \
  ubi --project rui314/mold $UBI_OPTS; \
  ubi --project boyter/scc $UBI_OPTS; \
  ubi --project mikefarah/yq $UBI_OPTS; \
  ubi --project wagoodman/dive $UBI_OPTS; \
  ubi --project bootandy/dust $UBI_OPTS; \
  ubi --project errata-ai/vale $UBI_OPTS; \
  ubi --project tilt-dev/tilt $UBI_OPTS; \
  ubi --project tilt-dev/ctlptl $UBI_OPTS; \
  ubi --project go-task/task $UBI_OPTS; \
  ubi --project twpayne/chezmoi $UBI_OPTS; \
  ubi --project cli/cli --exe gh $UBI_OPTS; \
  ubi --project immanuwell/dockerfile-roast --exe droast $UBI_OPTS; \
  bash /tmp/scripts/install-kubectl.sh v1.33.3; \
  ubi --project kubernetes-sigs/krew --rename-exe kubectl-krew $UBI_OPTS; \
  ubi --project kubernetes-sigs/cluster-api --exe clusterctl $UBI_OPTS; \
  ubi --project cilium/cilium-cli --exe cilium $UBI_OPTS; \
  ubi --project bitnami-labs/sealed-secrets --exe kubeseal $UBI_OPTS; \
  bash /tmp/scripts/install-helm.sh; \
  ubi --project fluxcd/flux2 --exe flux $UBI_OPTS; \
  ubi --project siderolabs/talos --exe talosctl $UBI_OPTS; \
  ubi --project oven-sh/bun $UBI_OPTS; \
  ln -sf /usr/local/bin/bun /usr/local/bin/bunx; \
  ubi --project ajeetdsouza/zoxide $UBI_OPTS; \
  userdel --remove ubuntu; \
  bash /tmp/scripts/setup-user.sh dev; \
  bash /tmp/scripts/configure-podman.sh dev; \
  unset GITHUB_TOKEN; \
  rm -rf \
    /tmp/* \
    $HOME/.cache/* \
    $HOME/.local/share/man/* \
    ;

COPY \
  common/resources/etc/ \
  images/dev/resources/etc/ \
  /etc/
RUN \
  set -xe; \
  sed -i 's/{{ USER }}/dev/' /etc/wsl.conf;

USER dev
WORKDIR /home/dev

COPY --chown=dev:dev \
  common/resources/tmp/ \
  /tmp/
RUN \
  set -xe; \
  bash /tmp/scripts/install-rust.sh; \
  # Install dotfiles
  chezmoi init --apply MLNW; \
  # Remove any sockets, e.g., created by tmux during plugin installation
  find /tmp -type s -delete; \
  # Configure krew on the user's shell
  echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' > $HOME/.oh-my-zsh/custom/krew.zsh; \
  kubectl krew install klock; \
  bash /tmp/scripts/install-mise.sh; \
  .local/bin/mise use -g node@22; \
  bash /tmp/scripts/configure-gitk.sh; \
  bash /tmp/scripts/install-claude.sh; \
  bash /tmp/scripts/configure-claude.sh; \
  rm -rf /tmp/*;

CMD [ "zsh" ]
